#!/usr/bin/env python3
"""Rebuild INDEX.md and manifest.json from the snippet library.

Walks library/<category>/<snippet-id>/metadata.yaml, validates the required
fields, and regenerates both indexes. Run after adding or changing a snippet.

No third-party dependencies required: if PyYAML is installed it is used,
otherwise a minimal parser handles the flat schema this repo uses.

Usage: scripts/reindex.py [--check]
  --check  exit non-zero if the generated files would change (for CI)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIBRARY = ROOT / "library"
INDEX_MD = ROOT / "INDEX.md"
MANIFEST = ROOT / "manifest.json"

REQUIRED = [
    "id", "title", "language", "category", "tags",
    "status", "description", "source", "dependencies", "created", "updated",
]


def parse_metadata(text: str) -> dict:
    """Parse metadata.yaml. Prefer PyYAML; fall back to a flat-schema parser."""
    try:
        import yaml  # type: ignore
        return yaml.safe_load(text) or {}
    except Exception:
        pass

    data: dict = {}
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            data[key] = [v.strip() for v in inner.split(",") if v.strip()]
        else:
            data[key] = value.strip("'\"")
    return data


def collect() -> list[dict]:
    snippets: list[dict] = []
    errors: list[str] = []

    if not LIBRARY.exists():
        return snippets

    for meta_path in sorted(LIBRARY.glob("*/*/metadata.yaml")):
        rel = meta_path.parent.relative_to(ROOT)
        meta = parse_metadata(meta_path.read_text())

        missing = [f for f in REQUIRED if not meta.get(f)]
        if missing:
            errors.append(f"{rel}: missing/empty fields: {', '.join(missing)}")

        folder_id = meta_path.parent.name
        if meta.get("id") and meta["id"] != folder_id:
            errors.append(f"{rel}: id '{meta.get('id')}' != folder '{folder_id}'")

        code_files = sorted(
            p.name for p in meta_path.parent.iterdir()
            if p.is_file() and p.name not in {"metadata.yaml", "notes.md"}
        )
        meta["path"] = str(rel)
        meta["files"] = code_files
        snippets.append(meta)

    if errors:
        sys.stderr.write("Validation problems found:\n")
        for e in errors:
            sys.stderr.write(f"  - {e}\n")

    return snippets


def render_index(snippets: list[dict]) -> str:
    lines = [
        "# Snippet index",
        "",
        "_Generated by `scripts/reindex.py` — do not hand-edit._",
        "",
        f"**{len(snippets)} snippet(s).**",
        "",
    ]

    by_cat: dict[str, list[dict]] = {}
    for s in snippets:
        by_cat.setdefault(s.get("category", "uncategorized"), []).append(s)

    for cat in sorted(by_cat):
        lines.append(f"## {cat}")
        lines.append("")
        lines.append("| id | title | lang | status | tags | description |")
        lines.append("|----|-------|------|--------|------|-------------|")
        for s in sorted(by_cat[cat], key=lambda x: x.get("id", "")):
            tags = ", ".join(s.get("tags", [])) if isinstance(s.get("tags"), list) else s.get("tags", "")
            link = f"[`{s.get('id','')}`]({s.get('path','')}/)"
            lines.append(
                f"| {link} | {s.get('title','')} | {s.get('language','')} "
                f"| {s.get('status','')} | {tags} | {s.get('description','')} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    snippets = collect()

    index_text = render_index(snippets)
    manifest_text = json.dumps(
        {"count": len(snippets), "snippets": snippets},
        indent=2, sort_keys=True, default=str,
    ) + "\n"

    if check:
        changed = False
        for path, new in ((INDEX_MD, index_text), (MANIFEST, manifest_text)):
            old = path.read_text() if path.exists() else None
            if old != new:
                changed = True
                sys.stderr.write(f"Out of date: {path.relative_to(ROOT)}\n")
        return 1 if changed else 0

    INDEX_MD.write_text(index_text)
    MANIFEST.write_text(manifest_text)
    print(f"Wrote INDEX.md and manifest.json ({len(snippets)} snippet(s)).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
